### ISSUE TITLE
Gravity bug

### ISSUE THREAD

**Issue by rbooth200** [Schulik/aiolos#3]
The enclosed mass calculation is not correct - it does not include contributions from previous cells unless self-gravity is turned on. Also, the mass in a single volume should be computed as density * volume, i.e. density * (r_{i+1}^3 - r_i^3) / 3. Factors of 4 * pi can be ignored entirely in a spherical code. See here:

https://github.com/Schulik/aiolos/blob/7c3cceac0a544097eed3b15d48827994d200f052/source.cpp#L53

**Comment by Schulik** [comment]
I fixed that yesterday actually, is that out of date in the spherical branch??

**Comment by Schulik** [comment]
Updating the mass only in the case of self-gravity is intentional - because in all cases phi = grav(r, m(r)); but I guess we can switch that to an if-clause with grav(r,m(0))  and grav(r,m(r))

**Comment by rbooth200** [comment]
Ok - looks like I had an out of date version
